"""add session disavow flag

Revision ID: 33ebc0607ac1
Revises: adffa455220c
Create Date: 2024-09-13 21:15:43.043685

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "33ebc0607ac1"
down_revision: Union[str, None] = "adffa455220c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recital_sessions", sa.Column("disavowed", sa.Boolean(), nullable=True))
    op.execute("UPDATE recital_sessions SET disavowed = false")
    op.alter_column('recital_sessions', 'disavowed', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recital_sessions", "disavowed")
    # ### end Alembic commands ###
