"""add document lang

Revision ID: 3e89168f53b0
Revises: b4257de1d215
Create Date: 2024-10-30 19:49:01.752227

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "3e89168f53b0"
down_revision: Union[str, None] = "b4257de1d215"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("text_documents", sa.Column("lang", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE text_documents SET lang = 'he'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("text_documents", "lang")
    # ### end Alembic commands ###
