"""add session duration column

Revision ID: 6b1c4c8aa754
Revises: 85bb1748266d
Create Date: 2024-09-18 10:16:55.896084

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "6b1c4c8aa754"
down_revision: Union[str, None] = "85bb1748266d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recital_sessions", sa.Column("duration", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recital_sessions", "duration")
    # ### end Alembic commands ###
