"""add document public flag

Revision ID: b4257de1d215
Revises: e53628a150e6
Create Date: 2024-10-06 20:09:05.505092

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "b4257de1d215"
down_revision: Union[str, None] = "e53628a150e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("text_documents", sa.Column("public", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("text_documents", "public")
    # ### end Alembic commands ###
