"""add user agreement cols

Revision ID: e53628a150e6
Revises: 6b1c4c8aa754
Create Date: 2024-09-30 08:45:24.671502

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "e53628a150e6"
down_revision: Union[str, None] = "6b1c4c8aa754"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("agreement_signed_version", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("users", sa.Column("agreement_signed_at", sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "agreement_signed_at")
    op.drop_column("users", "agreement_signed_version")
    # ### end Alembic commands ###
